web/router.ex
defmodule IceNarwhal.Router do
  use IceNarwhal.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug IceNarwhal.CurrentUser

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IceNarwhal do
    pipe_through [:browser, :session] # Use the default browser stack

    get "/", PageController, :index

    post "/shards/create", ShardController, :create

    resources "/users", UserController, only: [:show, :new, :create]

    resources "/sessions", SessionController, only: [:new, :create, :delete]

    resources "/fragments", FragmentController, only: [:show, :new, :create]

  end

  # Other scopes may use custom stacks.
  # scope "/api", IceNarwhal do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule IceNarwhal.LayoutView do
  use IceNarwhal.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Ice Narwhal</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">

        <a class='ice' href='/'>narwhal</a>
        <nav> 
          <%= if @current_user do %>
            <li><%= link "Logout", to: session_path(@conn, :delete, @current_user), method: "delete" %></li>
            <li class='current_user'><%= @current_user.tag %></li>
          <% else %>
            <li><%= link "Login", to: session_path(@conn, :new) %></li>
            <li><%= link "Join", to: user_path(@conn, :new) %></li>
          <% end %>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      
      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>