web/router.ex
defmodule IceNarwhal.Router do
  use IceNarwhal.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug IceNarwhal.CurrentUser

  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IceNarwhal do
    pipe_through [:browser, :session] # Use the default browser stack

    get "/", PageController, :index

    post "/shards/create", ShardController, :create

    resources "/users", UserController, only: [:show, :new, :create]

    resources "/sessions", SessionController, only: [:new, :create, :delete]

    resources "/fragments", FragmentController, only: [:show, :new, :create]

  end

  # Other scopes may use custom stacks.
  # scope "/api", IceNarwhal do
  #   pipe_through :api
  # end
end

web/templates/page/home.html.eex
<%= for fragment <- @current_user.fragments do %>
  <a href=<%= fragment_path(IceNarwhal.Endpoint, :show, fragment) %>>
  <div class='fragment'>
    <h2><%= fragment.label %></h2>
  </div>
  </a>
<% end %>

  <a href=<%= fragment_path(IceNarwhal.Endpoint, :new) %>>
  <div class='fragment fragment-plus'>
    <h2>+</h2>
  </div>
  </a>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2 class='intro-header'><span class='ice'>narwhal</span></h2>
  <p class="lead">Elegant note taking without all the clutter.</p>
</div>